version: '3.9'

services:
  postgres:
    image: postgres:15.2-alpine3.17
    container_name: pm-report_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
    ports:
      - '5466:5432'
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - report

  php:
    image: php_pm-report
    container_name: pm-report_php
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - '9000:9000'
    environment:
      - POSTGRES_DB= 'app'
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
    volumes:
      - .:/var/www
      - /app/vendor
    depends_on:
      - postgres
    networks:
      - report

  nginx:
    image: nginx:stable-alpine
    container_name: pm-report_nginx
    ports:
      - '9090:80'
    depends_on:
      - php
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf  
    restart: unless-stopped
    networks:
      - report

networks:
  report:
    external: false
