nelmio_api_doc:
    documentation:
        info:
            title: Symfony Party
            description: API Interface for fun app
            version: 1.0.0
        components:
            schemas:
                ApiException:
                    type: object
                    properties:
                        status:
                            type: integer
                            description: HTTP код ответа сервера.
                        message:
                            type: string
                            description: Сообщение об ошибке.
                        detail:
                            type: string
                            description: Подробное описание ошибки.
                        validationError:
                            type: object
                            properties:
                                body:
                                    type: array
                                    description: Параметры из body.
                                    items:
                                        type: object
                                        properties:
                                            name:
                                                type: string
                                                description: Название отправленного параметра.
                                            message:
                                                type: string
                                                description: Текст ошибки валидации по этому параметру (null == ошибки нет).

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
